name: Run Telegram Bot

on:
  schedule:
    - cron: "0 */4 * * *"  # هر 15 دقیقه یک بار اجرا می‌شود
  push:
    branches:
      - main  # اجرا هنگام push به شاخه main
  workflow_dispatch:  # امکان اجرای دستی در GitHub Actions

concurrency:
  group: telegram-bot
  cancel-in-progress: true  # اگر job قبلی هنوز در حال اجراست، آن را متوقف کن

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # دریافت کدهای پروژه

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # استفاده از نسخه پایدار پایتون

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot mysql-connector-python


      - name: Run Python script with Secret
        env:
          API_KEY: ${{ secrets.BOT_KEY }}
          ADMIN: ${{ secrets.ADMIN_ID }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}

        run: python main.py  # اجرا کردن اسکریپت اصلی
